install.packages(
  c("arrow",
    "babynames", 
    "curl", 
    "duckdb", 
    "gapminder", 
    "ggrepel", 
    "ggridges",
    "ggthemes",
    "hexbin",
    "janitor",
    "Lahman", 
    "leaflet",
    "maps",
    "nycflights13",
    "openxlsx",
    "pacman",
    "palmerpenguins", 
    "remotes",
    "repurrrsive", 
    "styler",
    "tidymodels",
    "tidyverse"
    "writexl",)
  )

# install.packages("remotes")
remotes::install_github("devOpifex/r.nvim")
remotes::install_github("jalvesaq/colorout")
